spring:
  config:
    activate:
      on-profile: dev
  application:
    name: dive-trip-application
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/dive_trip?characterEncoding=UTF-8
    username: master
    password: 1234
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

spring-doc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
    doc-expansion: list
  api-docs:
    path: /api-docs
    resolveSchemaProperties: true

logging:
  level:
    root: info
    io:
      divetrip: debug
    org:
      springframework: debug
      hibernate:
        sql: debug
        orm:
          jdbc:
            bind: trace

props:
  jwt:
    header: Authorization
    #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
    secret: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
    token-validity-in-seconds: 86400 # ttl (초): 60 * 60 * 24

